services:
  db:
    image: postgres:15
    container_name: pc-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: estoque_db
    #volumes:
    #  - db_data:/var/lib/postgresql/data
    restart: unless-stopped
# Comando para rodar o compose
#docker-compose up -d --build

# Comando para parar a aplicação
#docker-compose down
