### Variaveis de Ambiente

@hostname=localhost
@port=8000

@BASE_URL={{hostname}}:{{port}}/api


### Listar todos os itens do estoque

GET http://{{BASE_URL}}/estoque HTTP/1.1
Accept: application/json
