### Variaveis de Ambiente

@hostname=localhost
@port=8000

@BASE_URL = http://{{hostname}}:{{port}}/api

@seller_id = string123
@sku = sku123
@quantidade = 10

### Listar todos os itens do estoque
GET {{BASE_URL}}/estoque HTTP/1.1
Accept: application/json

### List Estoque
GET {{BASE_URL}}/estoque/list_estoque_api_estoque_get
Accept: application/json

### Create Estoque
POST {{BASE_URL}}/estoque/create_estoque_api_estoque_post
Content-Type: application/json
Accept: application/json

{
  "seller_id": "{{seller_id}}",
  "sku": "{{sku}}",
  "quantidade": {{quantidade}}
}

### List Estoque By Seller And Sku
GET {{BASE_URL}}/estoque/list_estoque_by_seller_and_sku_api_estoque_seller_id__sku__get?seller_id={{seller_id}}&sku={{sku}}
Accept: application/json

### Update Estoque By Seller And Sku
PATCH {{BASE_URL}}/estoque/update_estoque_by_seller_and_sku_api_estoque_seller_id__sku__patch?seller_id={{seller_id}}&sku={{sku}}
Content-Type: application/json
Accept: application/json

{
  "quantidade": {{quantidade}}
}

### Delete Estoque By Seller And Sku
DELETE {{BASE_URL}}/estoque/delete_estoque_by_seller_and_sku_api_estoque_seller_id__sku__delete?seller_id={{seller_id}}&sku={{sku}}
Accept: application/json