@hostname = localhost
@port = 8000
@BASE_URL = http://{{hostname}}:{{port}}/seller/v1/estoque

@seller_id = string123
@sku = sku123
@quantidade = 10

@seller_id_inexistente = naoexiste
@sku_inexistente = sku999

### Operações válidas 

### Criar item no estoque (esperado: 201 Created)
POST {{BASE_URL}}
Content-Type: application/json
Accept: application/json

{
  "seller_id": "loja1",
  "sku": "produto100",
  "quantidade": 15
}

### Listar todos os itens do estoque (esperado: 200 OK)
GET {{BASE_URL}}
Accept: application/json

### Listar item por seller_id e sku (esperado: 200 OK)
GET {{BASE_URL}}/loja1/produto100
Accept: application/json

### Atualizar quantidade do item (esperado: 200 OK)
PATCH {{BASE_URL}}/loja1/produto100
Content-Type: application/json
Accept: application/json

{
  "quantidade": 20
}

### Deletar item (esperado: 204 No Content)
DELETE {{BASE_URL}}/loja1/produto100
Accept: application/json

### Operações inválidas

### Criar item com seller_id vazio
POST {{BASE_URL}}
Content-Type: application/json
Accept: application/json

{
  "seller_id": "",
  "sku": "sku123",
  "quantidade": 10
}

### Criar item com sku vazio
POST {{BASE_URL}}
Content-Type: application/json
Accept: application/json

{
  "seller_id": "seller123",
  "sku": "",
  "quantidade": 10
}

### Criar item com quantidade negativa
POST {{BASE_URL}}
Content-Type: application/json
Accept: application/json

{
  "seller_id": "seller123",
  "sku": "sku123",
  "quantidade": -5
}

### Atualizar item com quantidade negativa
PATCH {{BASE_URL}}/loja1/produto100
Content-Type: application/json
Accept: application/json

{
  "quantidade": -5
}

### Criar item sem quantidade
POST {{BASE_URL}}
Content-Type: application/json
Accept: application/json

{
  "seller_id": "vendedor1",
  "sku": "produto1"
}

### Criar item com quantidade como string
POST {{BASE_URL}}
Content-Type: application/json
Accept: application/json

{
  "seller_id": "vendedor2",
  "sku": "produto2",
  "quantidade": "abc"
}

### Criar item com quantidade null
POST {{BASE_URL}}
Content-Type: application/json
Accept: application/json

{
  "seller_id": "vendedor3",
  "sku": "produto3",
  "quantidade": null
}


### Criar item com seller_id nulo
POST {{BASE_URL}}
Content-Type: application/json
Accept: application/json

{
  "seller_id": null,
  "sku": "produto4",
  "quantidade": 10
}

### Criar item com sku nulo
POST {{BASE_URL}}
Content-Type: application/json
Accept: application/json

{
  "seller_id": "vendedor5",
  "sku": null,
  "quantidade": 10
}

### Testes com itens inexistentes

### Tentar atualizar um item que não existe
PATCH {{BASE_URL}}/{{seller_id_inexistente}}/{{sku_inexistente}}
Content-Type: application/json
Accept: application/json

{
  "quantidade": 20
}

### Tentar deletar um item que não existe
DELETE {{BASE_URL}}/{{seller_id_inexistente}}/{{sku_inexistente}}
Accept: application/json


### Listar item inexistente
GET {{BASE_URL}}/{{seller_id_inexistente}}/{{sku_inexistente}}
